-- 코드를 입력하세요
SELECT DISTINCT A.USER_ID, B.PRODUCT_ID
FROM ONLINE_SALE AS A
INNER JOIN ONLINE_SALE AS B
ON A.PRODUCT_ID=B.PRODUCT_ID
where A.ONLINE_SALE_ID<>B.ONLINE_SALE_ID
 AND A.USER_ID=B.USER_ID
order by USER_ID, PRODUCT_ID desc
